version:
    version: "./scripts/__about__.py"
    changelog: "CHANGELOG.md"
    mode: "datetime"
git:
    commit_prefix:
    - ["comment", "Documents", ":bulb:"]  # 💡
    - ["typos", "Documents", ":pencil2:"]  # ✏️
    - ["summary", "Documents", ":pencil:"]  # 📝
    - ["refs", "References", ":clipboard:"]  # 📋, 📎 :paperclip:
    - ["conf", "Code Changes", ":seedling:"]  # 🌱
    commit_prefix_group:
    - ["Features", ":tada:"]  # 🎉
    - ["References", ":scissors:"]  # ✂️, 📁 :file_folder:
    - ["Documents", ":book:"]  # 📖
