version:
  version: "./scripts/__about__.py"
  changelog: "CHANGELOG.md"
  mode: "datetime"
git:
  commit_prefix:
    - ["comment", "Documents", ":bulb:"]  # 💡
    - ["typos", "Documents", ":pencil2:"]  # ✏️
  commit_prefix_group:
    - ["Features", ":tada:"]  # 🎉
