default_install_hook_types: [pre-commit, commit-msg]
default_language_version:
  python: python3.8

ci:
  skip: [shelf-commit-msg, compress-hook]
  autofix_commit_msg: |
    🚧 [pre-commit.ci] auto fixes from pre-commit.com hooks
  autofix_prs: true
  autoupdate_schedule: weekly
  autoupdate_commit_msg: |
    🚧 [pre-commit.ci] pre-commit autoupdate
  submodules: false

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.1
    hooks:
      - id: pyupgrade
        args: ["--py38-plus", "--keep-runtime-typing"]
        stages: [commit]

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        stages: [commit]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
        args: ["--fix"]
        stages: [commit]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: fix-byte-order-marker
        stages: [commit]
      - id: trailing-whitespace
        stages: [commit]
        exclude: ".bumpversion.cfg"
      - id: end-of-file-fixer
        stages: [commit]
      - id: check-yaml
        stages: [commit]
        args: ["--unsafe"]
      - id: check-toml
        stages: [commit]
      - id: requirements-txt-fixer
        stages: [commit]

  - repo: https://github.com/korawica/clishelf
    rev: v0.1.8
    hooks:
      - id: shelf-commit-msg
        stages: [commit-msg]

#  - repo: https://github.com/pre-commit/mirrors-prettier
#    rev: v4.0.0-alpha.8
#    hooks:
#      - id: prettier
#        types_or:
#          - toml
#          - css
#          - json
#          - json5
#          - yaml
#          - markdown
#        additional_dependencies:
#          - prettier
#          - prettier-plugin-toml
#        minimum_pre_commit_version: 2.9.0
#        exclude: ^(locale|CHANGELOG)
#        stages: [commit]
#  - repo: https://github.com/tcort/markdown-link-check
#    rev: v3.11.2
#    hooks:
#      - id: markdown-link-check
#        name: markdown-link-check
#        files: \.md$
#        args: ["-q", "--config", ".markdown-link-check.json"]
#        stages: [commit]
  - repo: local
    hooks:
      - id: compress-hook
        name: compress files on assets
        stages: [commit]
        types: [python]
        entry: venv/Scripts/python.exe scripts/compress.py
        language: system
        always_run: true
