site_name: Data Developer & Engineer
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/library-shelves
    repo: fontawesome/brands/github-alt

repo_name: korawica/ddedocs
repo_url: https://github.com/korawica/ddedocs

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/korawica/ddedocs

nav:
  - Home:
      - index.md
  - Basics:
      - basics/index.md
      - Tools:
          - Git:
              - basics/git/index.md
              - Commands:
                  - Common: basics/git/git-cmd-common.md
                  - Advance: basics/git/git-cmd-advance.md
              - Scenarios: basics/git/git-common-scenarios.md
              - Strategies:
                  - Branching Strategies: basics/git/git-branching-strategies.md
                  - Commit Release: basics/git/git-commit-release.md
          - Docker:
              - basics/docker/index.md
              - Commands:
                  - Management: basics/docker/docker-cmd-management.md
          - Pandas:
              - basics/pandas/index.md
          - AirFlow:
              - basics/airflow/index.md
          - ChatGPT:
              - basics/chatgpt/index.md
      - Knowledge:
          - Shell:
              - basics/shell/index.md
          - PowerShell:
              - basics/powershell/index.md
          - Python:
              - basics/python/index.md
              - Wheel: basics/python/py-dependency-wheel.md
              - Joblib: basics/python/py-joblib.md
          - Data:
              - basics/data/index.md
              - Data Observability: basics/data/data-ops-data-observability.md
              - Data Warehouse:
                  - basics/data/data_warehouse/index.md
              - Data Model:
                  - Bill Inmon:
                      - Normalization: basics/data/data_model/dml-normalization-form.md
                      - Model: basics/data/data_model/dml-3rd-normal-model.md
                  - Ralph Kimball:
                      - De-Normalization: basics/data/data_model/dml-denormalization-form.md
                      - Model: basics/data/data_model/dml-dimension-model.md
                      - Implement: basics/data/data_model/dml-dimension-model-implement.md
                  - Data Vault:
                      - Model: basics/data/data_model/dml-data-vault-model.md
                      - Implement: basics/data/data_model/dml-data-vault-model-implement.md
          - Analytic:
              - basics/analytic/index.md
      - Services:
          - GitHub:
              - basics/github/index.md
              - Actions: basics/github/github-actions.md
      - Connections:
          - Edge:
              - basics/edge/index.md
  - Advances:
      - advances/index.md
      - Tools:
          - Spark:
              - advances/spark/index.md
              - Bucketing: advances/spark/spark-bucketing.md
#              - advances/spark/spark-bucketing.md
#              - Pyspark:
#                  - advances/spark/pyspark/pyspark-scd2.md
          - Kubernetes:
              - advances/k8s/index.md
          - Ansible:
              - advances/ansible/index.md
          - Terraform:
              - advances/terraform/index.md
      - Knowledge:
          - GO:
              - advances/go/index.md
              - Command: advances/go/go-command.md
              - Unittest: advances/go/go-unittest.md
              - Connect Database: advances/go/go-database.md
              - Advances:
                  - Connect Kafka: advances/go/go-connect-kafka.md
                  - Connect Redis: advances/go/go-connect-redis.md
                  - Hexagonal Architect: advances/go/go-hexagonal-architecture.md
      - Services:
          - Azure:
              - advances/azure/index.md
              - Batch:
                  - Auto Scalable: advances/azure/batch/az-btch-auto-scalable.md
                  - Access Key Vault: advances/azure/batch/az-btch-access-key-vault.md
                  - Run Pyspark With Docker: advances/azure/batch/az-btch-run-pyspark-with-docker.md
                  - Docker mode: advances/azure/batch/az-btch-run-docker.md
                  - Docker inside Node: advances/azure/batch/az-btch-run-docker-inside.md
              - Function App:
                  - Access Key Vault: advances/azure/functions/azf-access-key-vault.md
                  - Access Synapse SQL Pool: advances/azure/functions/azf-access-synapse-sql-pool.md
                  - Access Service Bus: advances/azure/functions/azf-access-service-bus.md
              - Databricks:
                  - Init Script: advances/azure/databricks/adb-init-script.md
                  - Mount Storage: advances/azure/databricks/adb-mount-storage.md
              - Data Factory:
                  - Link MongoDB: advances/azure/data_factory/adf-lsv-mongodb.md
              - Synapse Analytic:
                  - Authentication: advances/azure/synapse/asa-authentication.md
                  - External Data: advances/azure/synapse/asa-external-data.md
                  - Partition View: advances/azure/synapse/asa-partition-view.md
                  - Operations: advances/azure/synapse/asa-operations.md
              - DevOps:
#                  - CICD Batch:
                  - CICD Function App: advances/azure/devops/devops-cicd-az-afn.md
                  - CICD Databricks: advances/azure/devops/devops-cicd-az-adb.md
                  - CICD Data Factory: advances/azure/devops/devops-cicd-az-adf.md
#                  - CICD Synapse Analytic:
                  - CICD Power BI: advances/azure/devops/devops-cicd-az-pbi.md
                  - Self Hosted:
                      - Deploy Python App: advances/azure/devops/devops-cicd-self-hosted-win-fastapi.md
          - AWS:
              - advances/aws/index.md
              - IoT:
                  - Rule to S3: advances/aws/iot_core/iot-rule-to-s3.md
                  - Rule to Kinesis: advances/aws/iot_core/iot-rule-to-kinesis.md
#              - Glue:
#                  - ??
          - Google:
              - advances/google/index.md
#              - Big Query:
#                  - ??
  - Usecases:
      - usecases/index.md
      - Architect:
          - AWS Serverless Data Analytic: usecases/architect/act-aws-serverless-data-analytics-pipeline.md
          - Azure Modern Data Pipeline: usecases/architect/act-azure-modern-data-pipeline.md
          - Azure Data Mesh: usecases/architect/act-data-mesh-with-azure.md
          - Stream Processing: usecases/architect/act-open-source-stream-processing.md

plugins:
  - tags
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables

copyright: |
  &copy; 2023 <a href="https://github.com/korawica/ddedocs"  target="_blank" rel="noopener">Korawich Anuttra</a>
