site_name: Data Developer & Engineer
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/library-shelves
    repo: fontawesome/brands/github-alt

repo_name: korawica/ddedocs
repo_url: https://github.com/korawica/ddedocs

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/korawica/ddedocs

nav:
  - Home:
      - index.md
  - Basics:
      - basics/index.md
      - Tools:
          - Git:
              - basics/git/index.md
              - Commands: basics/git/git-cmd-common.md
              - Scenarios: basics/git/git-common-scenarios.md
              - Strategies:
                  - Branching Strategies: basics/git/git-branching-strategies.md
                  - Commit Release: basics/git/git-commit-release.md
          - Docker:
              - basics/docker/index.md
          - ChatGPT:
              - basics/chatgpt/index.md
      - Knowledge:
          - Python:
              - basics/python/index.md
          - Data:
              - basics/data/index.md
              - Data Warehouse:
                  - basics/data/data_warehouse/index.md
                  - Data Vault:
                      - Model: basics/data/data_warehouse/dwh-data-vault-model.md
                      - Implement: basics/data/data_warehouse/dwh-data-vault-model-implement.md
                  - Ralph Kimball:
                      - Model: basics/data/data_warehouse/dwh-dimension-model.md
                      - Implement: basics/data/data_warehouse/dwh-dimension-model-implement.md
                  - Bill Inmon:
                      - Model: basics/data/data_warehouse/dwh-3rd-normal-model.md
      - Services:
          - GitHub:
              - basics/github/index.md
              - Actions: basics/github/github-actions.md
      - Connections:
          - On Premise:
              - basics/on-premise/index.md
  - Advances:
      - advances/index.md
      - Tools:
          - Spark:
              - advances/spark/index.md
              - Bucketing: advances/spark/spark-bucketing.md
#              - advances/spark/spark-bucketing.md
#              - Pyspark:
#                  - advances/spark/pyspark/pyspark-scd2.md
          - Kubernetes:
              - advances/k8s/index.md
      - Knowledge:
          - GO:
              - advances/go/index.md
      - Services:
          - Azure:
              - advances/azure/index.md
              - Batch:
                  - Auto Scalable: advances/azure/batch/az-btch-auto-scalable.md
                  - Access Key Vault: advances/azure/batch/az-btch-access-key-vault.md
              - Databricks:
                  - Init Script: advances/azure/databricks/adb-init-script.md
                  - Mount Storage: advances/azure/databricks/adb-mount-storage.md
              - Synapse Analytic:
                  - Authentication: advances/azure/synapse/asa-authentication.md
                  - External Data: advances/azure/synapse/asa-external-data.md
                  - Partition View: advances/azure/synapse/asa-partition-view.md
                  - Operations: advances/azure/synapse/asa-operations.md
              - DevOps:
                  - Self Hosted:
                      - Deploy Python App: advances/azure/devops/cicd-self-hosted-win-fastapi.md
          - AWS:
              - advances/aws/index.md
#              - Glue:
#                  - ??
          - Google:
              - advances/google/index.md
#              - Big Query:
#                  - ??
  - Usecases:
      - usecases/index.md

plugins:
  - tags
  - search

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables
  - md_in_html

copyright: |
  &copy; 2023 <a href="https://github.com/korawica/ddedocs"  target="_blank" rel="noopener">Korawich Anuttra</a>
