authors:
  admin:
    name: Korawich Anuttra
    description: Admin
    avatar: https://github.com/ddeutils/ddedocs/tree/main/assets/img/dde.png
#    slug: url           # Author profile slug
#    url: url            # Author website URL
