name: ci

on:
  push:
    tags:
      - "*"
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: python-${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          pip install -U pip
          pip install -r requirements.txt
          pip install pillow cairosvg

      - name: Deploy GitHub Page
        run: |
          mkdocs gh-deploy --force
