name: gitleaks

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:
    branches:
      - main
#  schedule:
#    - cron: "0 4 * * *"  # run once a day at 4 AM

jobs:

  validate:

    runs-on: ubuntu-latest
    steps:

    - name: Code checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
