name: publish

on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout all of contents
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: python-${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          pip install -U pip
          pip install -r requirements.txt
          pip install pillow cairosvg

      - name: Deploy GitHub Page
        env:
          CI: true
        run: |
          mkdocs gh-deploy --force
