name: scan

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:
    branches:
      - main
#  schedule:
#    - cron: "0 4 * * *"  # run once a day at 4 AM

jobs:

  gitleaks:

    runs-on: ubuntu-latest
    continue-on-error: true

    steps:

    - name: Code checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}


  trufflehog:
    runs-on: ubuntu-latest

    steps:

    - name: Code checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --results=verified,unknown
